server:
  port: 9001
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user  #服务名称"唯一"
  registry:
    address: zookeeper://192.168.28.130:2181?backup=192.168.28.130:2182,192.168.28.130:2183